# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Self-Hosted Deploy

on:
  push:
    branches: [ develop ] # for now
  workflow_dispatch:


jobs:
  deploy:
    runs-on: [self-hosted, Linux]
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add env vars
        run: |
          echo '${{ secrets.PYTHON_ENV }}' > .env
      - name: Build
        run: |-
          docker build . -t app
      - name: Kill all other dockers (only other image deployed atm)
        continue-on-error: true
        run: |
          docker kill $(docker ps -q)
      - name: Run
        run: |-
          docker run -d app
